version: '3'

services:
  postgres:
    container_name: marketplace_test_database
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_marketplace
    ports:
      - '5432:5432'

  debug-helper:
    image: busybox
