version: '3'

services:
  postgres_test_db:
    container_name: marketplace_test_database
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: test_marketplace
    ports:
      - '5432:5432'

  debug-helper:
    image: busybox
