interface EnvVariables {
  VITE_CLOUDINARY_UPLOAD_PRESET: string;
  VITE_CLOUDINARY_UPLOAD_URL: string;
}

const {
  VITE_CLOUDINARY_UPLOAD_PRESET: CLOUDINARY_UPLOAD_PRESET,
  VITE_CLOUDINARY_UPLOAD_URL: CLOUDINARY_UPLOAD_URL,
} = import.meta.env as unknown as EnvVariables;

export { CLOUDINARY_UPLOAD_PRESET, CLOUDINARY_UPLOAD_URL };
