name: Deployment pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm run install-all

      - name: Check style
        run: run npm run lint

      - name: Create production builds
        run: npm run build

      - name: Run unit tests
        run: cd client && npm test

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_APP_EMAIL}}
          procfile: 'web: npm start'
          healthcheck: 'https://donewithit-marketplace-6ab68864c928.herokuapp.com/health'
          checkstring: 'ok'
          delay: 5
          rollbackonhealthcheckfailed: true

  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
